Set PARAM_DFLT to 500 for radius
When running with no radius param 0 seems to be used. Unfortunately
it causes a failure in elastic:
  IllegalArgumentException: invalid radiusMeters 0.0

Set PARAM_DFLT to MIN_RADIUS so that the MIN/MAX range is always
respected.

Change-Id: Iec08f60dd0d8fbf196e554d116354846f3c9e1a9